# Prometheus 配置文件
# 用于收集 MicroRadar 指标

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'microradar-monitor'

# 告警规则文件
rule_files:
  - "alert_rules.yml"

# 告警管理器配置
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# 抓取配置
scrape_configs:
  # MicroRadar 主服务
  - job_name: 'microradar'
    static_configs:
      - targets: ['microradar:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s
    
    # 标签
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: microradar:8080

  # Prometheus 自身
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # 节点导出器 (如果有)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    
    # 仅在节点导出器可用时启用
    honor_labels: true
    
  # Docker 导出器 (如果有)
  - job_name: 'docker-exporter'
    static_configs:
      - targets: ['docker-exporter:9323']
    scrape_interval: 15s

# 存储配置
storage:
  tsdb:
    retention.time: 7d
    retention.size: 1GB
